config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/show'
  resources :services

  root 'home#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: services
#
#  id               :integer          not null, primary key
#  description      :text
#  dns_name         :string
#  ip               :string
#  name             :string
#  port             :integer
#  serviceable_type :string
#  url              :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  serviceable_id   :integer
#

class Service < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def show; end
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show; end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit; end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:name,
                                    :dns_name,
                                    :ip,
                                    :url,
                                    :port,
                                    :serviceable_id,
                                    :serviceable_type,
                                    :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/show.html.erb
<div class="row justify-content-center">
  <div class="col-xs-12">
    <br />
    <h1>Home#show</h1>
    <p>Find me in app/views/home/show.html.erb</p>
  </div>
</div>

app/views/layouts/_body.html.erb
<body>
<%= render 'layouts/navbar' %>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-xs-12">
      <% render 'layouts/notice' %>
    </div>
  </div>
  <%= yield %>
</div>
</body>

app/views/layouts/_header.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="scytherswings">

  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <!-- Bootstrap Core CSS -->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Custom CSS -->
</head>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Porthole</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse mr-auto" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Home', home_show_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Services', services_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<p id="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/header' %>
  <%= render 'layouts/body' %>
  <%#= render 'footer' %>
</html>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :dns_name %>
    <%= form.text_field :dns_name %>
  </div>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :port %>
    <%= form.number_field :port %>
  </div>

  <div class="field">
    <%= form.label :serviceable_id %>
    <%= form.number_field :serviceable_id %>
  </div>

  <div class="field">
    <%= form.label :serviceable_type %>
    <%= form.text_field :serviceable_type %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<div class="row justify-content-center">
  <div class="col-xs-12">
    <br />

    <h1>Services</h1>

    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Dns name</th>
        <th>IP</th>
        <th>Url</th>
        <th>Port</th>
        <th>Service Type</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.name %></td>
          <td><%= service.dns_name %></td>
          <td><%= service.ip %></td>
          <td><%= service.url %></td>
          <td><%= service.port %></td>
          <td><%= service.serviceable_type %></td>
          <td><%= service.description %></td>
          <td><%= link_to 'Show', service, class: 'btn btn-info' %></td>
          <td><%= link_to 'Edit', edit_service_path(service), class: 'btn btn-info' %></td>
          <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Service', new_service_path, class: 'btn btn-success' %>

  </div>
</div>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Dns name:</strong>
  <%= @service.dns_name %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @service.ip %>
</p>

<p>
  <strong>Url:</strong>
  <%= @service.url %>
</p>

<p>
  <strong>Port:</strong>
  <%= @service.port %>
</p>

<p>
  <strong>Serviceable:</strong>
  <%= @service.serviceable_id %>
</p>

<p>
  <strong>Serviceable type:</strong>
  <%= @service.serviceable_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>